version: '3.1'
services:
  db-postgresql:
   image: salihcantekin/postgres
   restart: on-failure
   ports:
    - 2345:5432
   networks:
    - my_swarm_net
   environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=241990
   volumes:
    - /mnt/nfs_shares/docker_app_data/postgresql:/var/lib/postgresql/data
   deploy:
    replicas: 2
    restart_policy:
      max_attempts: 3
      condition: on-failure
    placement: 
     constraints: 
       - node.role == worker

  crmapi:
   build: .
   image: salihcantekin/crmapi
   ports:
    - 90:1000
    - 91:1001
   
   depends_on:
     - db-postgresql
   environment:
     - ASPNETCORE_ENVIRONMENT=Production
   networks:
    - my_swarm_net
   deploy:
    replicas: 2
    restart_policy:
      max_attempts: 3
      condition: on-failure
    placement: 
     constraints: 
       - node.role == worker

networks:
  my_swarm_net: