version: '3.1'
services:
  #db-postgresql:
  # image: salihcantekin/postgres
  # restart: on-failure
  # ports:
  #  - "5432:5432" 
  # networks:
  #  - mynet
  # environment:
  #  - PGDATA=/var/lib/postgresql/data/pgdata
  #  - POSTGRES_USER=postgres
  #  - POSTGRES_PASSWORD=241990
  # volumes:
  #  - /opt/app_data/postgresql:/var/lib/postgresql/data

  crmapi:
   build: .
   image: salihcantekin/crmapi
   ports:
    - "90:1000"
   #depends_on:
   #  - db-postgresql
   networks:
    - mynet
   deploy:
    replicas: 2
    restart_policy:
     condition: on-failure


networks:
  mynet:
    external: true